---
title: "Project"
author: "Shawn Riemer"
date: "11/11/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyr)
library(corrplot)
library(corrr)
```

## Read in Data

```{r}
country <- read_csv("data/Country.csv", col_types = cols())
ind <- read_csv("data/Indicators.csv", col_types = cols())
```

```{r}
# Each observation is uniquely identified by CountryName/CountryCode, IndicatorName/IndicatorCode, Year
# ind %>% str()
# ind$Year %>% unique()
ind <- ind %>% 
  mutate(
    IndicatorName = str_replace_all(IndicatorName, " ", "_")
  )
```

```{r}
ind2 <- ind %>%
  select(CountryName, IndicatorName, Year, Value) %>%
  pivot_wider(names_from = IndicatorName,
              values_from = Value,
              values_fill = NA)

mvt <- table(is.na(ind2))
(percent_missing_total <- mvt[1] / (mvt[1] + mvt[2]))

# ind$IndicatorCode %>% unique() %>% length()
# 1344
```

Number of missing values for each indicator
```{r}
max_percent_missing <- 0.8

# Filter to only have indicators that have less than max_percent_missing percent of missing values
sapply(ind2, function(x) sum(is.na (x))) %>% 
  as.data.frame() %>% 
  select(., everything()) %>% 
  mutate(
    p_missing = . / 13823
  ) %>% 
  arrange(-desc(.)) %>% 
  filter(p_missing < max_percent_missing)
```

Number of missing values per country
```{r}
# all_data_num <- ind$IndicatorName %>% unique() %>% length() * ind$Year %>% unique() %>% length()
# ind %>% group_by(
#   CountryName
# ) %>% summarise(
#   p_missing = 1 - n() / all_data_num
# ) %>% arrange(-desc(p_missing))

# ind2 %>% pivot_longer( cols = )
# ind2 %>%
#   select(everything()) %>%
#   summarise_all(funs(sum(is.na(.))))

n_d <- (ind2 %>% colnames() %>% length() - 2) * 56 # CountryName and Year don't count

ind2 %>% 
  group_by(CountryName) %>% 
  select(-Year) %>% 
  summarise_all(funs(sum(is.na(.)))) %>% 
  mutate(
    p_missing = select(., -CountryName) %>% rowSums() / n_d
  ) %>% select(
    CountryName,
    p_missing
  ) %>% arrange(-desc(p_missing))
```

We want to have some fraction of countries we remove and some fraction of indicators we remove such that the total number of missing values is low.





