---
title: "Project"
author: "Shawn Riemer"
date: "11/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidyr)
library(corrplot)
library(corrr)
```

```{r}
country = read.csv("data/Country.csv")
head(country, 3)
```

```{r}
ind = read.csv("data/Indicators.csv")
# head(ind, 3)
# ind %>% str()
ind$CountryName %>% unique() %>% length()
# ind$CountryCode %>% unique() %>% length()
ind$IndicatorName %>% unique() %>% length()
ind$IndicatorCode %>% unique() %>% length()
# ind$Year %>% unique() %>% length()
# ind$Value %>% length()
# ind$Value %>% is.na() %>% sum()
# summary(ind)
```


```{r}
mex <- ind %>% filter(CountryName == "Mexico")

mex_ <- mex %>% group_by(IndicatorCode) %>% 
  summarise(
    n = n(),
    CountryName,
    Year,
    IndicatorCode,
    IndicatorName = str_replace_all(IndicatorName, " ", "_"),
    Value
  ) %>% filter(n > 50) %>% ungroup()
```


```{r}
# mex2 <- mex_ %>% select(CountryName, Year, IndicatorCode, IndicatorName, Value) %>% 
mex2 <- mex_ %>% select(CountryName, Year, IndicatorCode, Value) %>%
# mex2 <- mex_ %>% select(CountryName, Year, IndicatorName, Value) %>%
pivot_wider(
  # names_from = IndicatorName,
  names_from = IndicatorCode,
  values_from = Value,
  values_fill = 0
)
mex2
```


```{r}
# mex3 <- mex2 %>% select(-c(CountryName, Year, IndicatorCode)) %>% 
mex3 <- mex2 %>% select(-c(CountryName, Year)) %>% 
  cor() %>% 
  round(digits = 2) %>% 
  data.frame()
mex3

code_to_name <- function(code) {
  uh <- ind %>% select(IndicatorName, IndicatorCode) %>% filter(IndicatorCode == code) %>% unique()
  uh$IndicatorName
}


code_to_name("AG.LND.ARBL.HA.PC")
code_to_name("EN.URB.MCTY")
code_to_name("NE.CON.PETC.CN")
code_to_name("")
code_to_name("")
code_to_name("")
code_to_name("")
code_to_name("")

# AG.LND.ARBL.HA.PC	

mex3['NY.GDP.PCAP.CD'] %>% filter(abs(NY.GDP.PCAP.CD) < 0.95 & abs(NY.GDP.PCAP.CD) > 0.3) %>% arrange(-abs(NY.GDP.PCAP.CD))
```


```{r}
# mex3['GDP_per_capita_(current_US$)	'] %>% arrange(GDP_per_capita_(current_US$))
# mex3['NY.GDP.PCAP.CD'] %>% arrange(NY.GDP.PCAP.CD)

mex3['NY.GDP.PCAP.CD'] %>% filter(abs(NY.GDP.PCAP.CD) > 0.95 & abs(NY.GDP.PCAP.CD) < 1) %>% arrange(NY.GDP.PCAP.CD)
# mex3['Land_area_(sq._km)'] %>% filter(abs(NY.GDP.PCAP.CD) > 0.9) %>% arrange(NY.GDP.PCAP.CD)

mex2_ <- mex2 %>% select(-c(CountryName, Year))

# corrplot.mixed(
#   round(cor(mex2_), 2),
#   lower = "number",
#   upper = "color"
# )
```


```{r}
# ind %>% group_by(CountryName) %>% 
#   summarise(
#     n_ind_many_year = group_by(IndicatorName) %>% 
#       summarise(
#         
#       )
#   )

ind %>% group_by(CountryName) %>% 
  summarise(
    n = n(),
    n_year = Year %>% unique() %>% length(),
    n_ind = IndicatorName %>% unique() %>% length()
  ) %>% arrange(n, n_ind)
```

```{r}
# what indicators are in ALL countries?
foo <- ind %>% group_by(IndicatorName) %>% 
  summarise(
    n = n(),
    n_count = CountryName %>% unique() %>% length()
  ) %>% arrange(-n_count) %>% 
  select(n_count, n, IndicatorName)
foo
foo %>% nrow()
```
```{r}
ind %>% group_by(IndicatorName) %>% 
  summarise(
    n_val = Value %>% length()
  ) %>% arrange(-n_val)
```



```{r}
foo %>% filter( n_count > 200)
```



```{r}
ind
ind %>%
  filter(CountryName=="United States" & IndicatorCode=="SP.ADO.TFRT") %>%
  ggplot(aes(x=Year, y=Value)) +
  geom_point()
```

```{r}
ind %>%
  filter(CountryName=="United States" & Year==2010)
```

```{r}
country
```

